### ISSUE TITLE
leecher will not enter baal tp on "NTConfig_TakeTpBaal"

### ISSUE THREAD

**Issue by erlipton05** [Project-Etal/D2Etal#2]
leech does not enter tp when parameters are met for NTConfig_TakeTpBaal

**Comment by acien** [comment]
try posting about this on the forums at http://www.projectetal.com/

**Comment by Villiyo** [comment]
is it difficult to launch a bot in the new version of Diablo path of diablo&?Hi(sorry for my English I use a translator) in the last season of Path of Diablo I used a remade D2 etal using d2 path. mpq (pod) in the folder with the vanilla version and it worked only needed an injector pod.dll /now an error occurred when trying to create a server or log in .https://www.youtube.com/watch?v=ijYdOmYUfaQ
